# Generated by Django 2.1.11 on 2019-08-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailstreamforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='form_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='form',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub_Title'),
        ),
    ]
